
OAUTH1_SERVICES = {'goodreads'}

SECRET_KEY = ""

DEFAULT_USER_EMAIL = ""

GOODREADS_CLIENT_ID = ""
GOODREADS_USERID = ""
GOODREADS_CLIENT_SECRET = ""

STRAVA_CLIENT_ID = 0
STRAVA_CLIENT_SECRET = ""

GSHEET_CLIENT_ID = ""
GSHEET_CLIENT_SECRET = ""
GSHEET_DOC_ID = ""

GOOGLEFIT_CLIENT_ID = ""
GOOGLEFIT_CLIENT_SECRET = ""

WITHINGS_CLIENT_ID = ""
WITHINGS_CLIENT_SECRET = ""
